### ISSUE TITLE
[Egg Request]: valheim + 

### ISSUE THREAD

**Issue by marindumont** [gOOvER/own-pterodactyl-eggs#5]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.9.17

### Links for the download

https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.9.17

### Links for the install docs

https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.9.17

### Are you willing to pay for this egg (Donation/Gamekey)?

Yes

**Comment by gOOvER** [comment]
fixed in parkers repo
